document.addEventListener('alpine:init', () => {
    Alpine.store('products', {
        searchQuery: '',
    });

    Alpine.data('produk', () => ({
        kategori: 'all',
        itemDetail: null,
        items: [
            {id: 1, name: 'Betuah Raye', img:'b_1.jpg', price: 25000, category: 'coffee', deskripsi: 'Rasakan Magisnya Kopi Susu Betuah Raye, Rahasia kelezatan kami ada pada perpaduan dua dunia: Arabica yang elegan dan Robusta yang berani Dibalut dengan susu creamy dalam kemasan cup yang praktis setiap tegukan memberikan sensasi rasa yang "betuah" dan membangkitkan semangat, Grab yours now and get that extra boost' },
            {id: 2, name: 'Batuah (Robusta)', img:'b_1.jpg', price: 18000, category: 'coffee', deskripsi: 'Pernahkah Anda mencoba kopi susu dengan tekstur selembut sutra namun tetap memiliki karakter kopi yang kuat? Kopi Susu Betuah hadir dengan racikan rahasia kami sendiri, menggabungkan kopi pilihan dengan komponen pelengkap yang membuatnya terasa begitu creamy dan rich. Temukan sensasi "betuah" yang sesungguhnya di setiap cup-nya!' },
            {id: 3, name: 'Gula Aren', img:'b_1.jpg', price: 20000, category: 'coffee', deskripsi: 'Temukan kesegaran Kopi Susu Gula Aren kami yang diracik dengan signature recipe untuk menciptakan tekstur yang begitu halus dan creamy. Perpaduan kopi pilihan yang kuat dengan manisnya gula aren asli memberikan sensasi yang bikin nagih dari tegukan pertama. Segera nikmati kelezatannya dalam kemasan cup yang siap menemani hari Anda!' },
            {id: 4, name: 'Butterscotch', img:'b_1.jpg', price: 20000, category: 'coffee', deskripsi: 'Butuh suntikan semangat dengan sentuhan rasa yang unik? Coba racikan spesial kami! Perpaduan kopi yang bold dengan aroma serta rasa butterscotch yang manis gurih, berpadu sempurna dalam tekstur yang sangat halus. Segar, nikmat, dan siap menemani hari produktif Anda. Take a sip and feel the magic!' },
            {id: 5, name: 'Caramel', img:'b_1.jpg', price: 20000, category: 'coffee', deskripsi: 'Nikmati perpaduan antara kopi dengan karakter yang kuat, diseimbangkan dengan manisnya caramel yang khas. Racikan spesial kami menghasilkan tekstur yang begitu halus dan memikat di setiap tegukannya. Dibuat dengan komposisi terbaik, memberikan pengalaman minum kopi yang mewah namun tetap kasual. Grab your cup and treat yourself today!' },
            {id: 6, name: 'Hazelnut', img:'b_1.jpg', price: 20000, category: 'coffee', deskripsi: 'Butuh teman untuk menjalani hari? Kopi Susu Hazelnut kami hadir dengan profil rasa yang bold namun tetap lembut di lidah. Sentuhan kacang hazelnut yang aromatik menyatu sempurna dalam racikan rahasia kami, menciptakan kenikmatan yang sulit dilupakan. Praktis, nikmat, dan siap menemani momen santai atau produktif Anda. Grab yours today!' },
            {id: 7, name: 'Cream Cheese', img:'b_2.jpg', price: 20000, category: 'coffee', deskripsi: 'Manjakan lidah Anda dengan sensasi kopi yang unik dan belum pernah Anda rasakan sebelumnya. Perpaduan karakter kopi pilihan yang kuat dengan sentuhan gurih dan creamy dari cream cheese premium. Racikan kami menciptakan tekstur yang lembut, velvety, dan begitu kaya akan rasa di setiap tegukannya.' },
            {id: 8, name: 'Tiramisu', img:'b_4.jpg', price: 20000, category: 'coffee', deskripsi: 'Kopi susu dengan sentuhan spesial cita rasa Tiramisu. Menawarkan perpaduan antara kekuatan kopi dengan aroma yang kaya dan tekstur yang sangat lembut. Dibuat dari bahan-bahan berkualitas tinggi untuk memberikan pengalaman minum kopi yang konsisten dan memanjakan. Nikmati kelezatan premium ini kapan saja, di mana saja.' },
            {id: 9, name: 'Banana', img:'b_4.jpg', price: 20000, category: 'coffee', deskripsi: 'Ingin menikmati kopi dengan twist yang berbeda? Kopi Susu Banana kami hadir dengan profil rasa yang bold namun lembut, dipadukan dengan sentuhan aroma buah tropis yang manis dan legit. Diracik khusus dengan formula rahasia kami untuk menghasilkan sensasi rasa yang halus, creamy, dan menyegarkan. A perfect companion for your sunny day!' },
            {id: 10, name: 'Pistachio', img:'b_4.jpg', price: 20000, category: 'coffee', deskripsi: 'Bosan dengan kopi susu biasa? Temukan kelembutan rasa pistachio yang gurih dan aromatik berpadu dengan kopi pilihan kami yang bold. Racikan spesial ini menawarkan keseimbangan rasa yang unik—manis, gurih, dan sangat lembut di setiap tegukannya. Sensasi creamy yang tak terlupakan menanti Anda di dalam setiap cup-nya. Taste the elegance!' },
            {id: 11, name: 'Coconut', img:'b_4.jpg', price: 20000, category: 'coffee', deskripsi: 'Kopi susu dengan sentuhan spesial cita rasa kelapa yang autentik. Menawarkan harmoni antara karakter kopi yang kuat dengan nuansa tropis yang lembut. Dibuat dari bahan-bahan berkualitas premium untuk menjamin konsistensi rasa yang kaya di setiap cup. Nikmati kesegaran istimewa yang akan memanjakan selera Anda.' },
            {id: 12, name: 'Almond', img:'b_4.jpg', price: 20000, category: 'coffee', deskripsi: 'Temukan harmoni rasa baru yang memanjakan lidah! Kopi Susu Almond kami hadir dengan profil rasa yang bold namun seimbang dengan nuansa kacang almond yang eksklusif. Formula rahasia kami menjamin tekstur yang velvety dan kaya rasa di setiap tegukan. Cocok bagi Anda yang mendambakan kopi dengan sentuhan rasa premium yang unik dan tidak terlupakan.' },
            {id: 13, name: 'Pandan', img:'b_4.jpg', price: 20000, category: 'coffee', deskripsi: 'Rasakan kedamaian dalam secangkir kopi dengan sentuhan aroma pandan yang ikonik. Perpaduan antara karakter kopi pilihan yang mantap dengan wangi pandan alami yang segar, menciptakan harmoni rasa yang lembut dan menenangkan. Racikan spesial kami menghasilkan tekstur yang sangat creamy dan smooth.' },
            {id: 14, name: 'Vanila', img:'b_5.jpg', price: 20000, category: 'coffee', deskripsi: 'Siapa yang bisa menolak perpaduan kopi dengan aroma vanilla yang ikonik? Kopi Susu Vanilla kami hadir dengan profil rasa yang seimbang, manisnya yang pas, serta tekstur yang begitu lembut. Dibuat dengan formula rahasia kami, setiap tegukan memberikan sensasi smooth yang bikin nagih. Cocok untuk Anda yang menyukai kopi dengan aftertaste yang manis dan nyaman di mulut.' },
            {id: 15, name: 'Kopi Madu', img:'b_5.jpg', price: 17000, category: 'coffee', deskripsi: 'Rasakan perpaduan harmonis antara karakter kopi yang bold dengan manisnya sentuhan alami yang lembut. Minuman ini menawarkan pengalaman menikmati kopi yang berbeda—lebih ringan, elegan, dan memberikan aftertaste yang manis di setiap tegukannya. Dihadirkan dalam kemasan cup yang praktis, ini adalah pilihan tepat bagi Anda yang menyukai kemurnian rasa dengan sentuhan kebaikan alam.' },
            {id: 16, name: 'Kopi Latte', img:'b_6.jpg', price: 16000, category: 'coffee', deskripsi: 'Rasakan keseimbangan sempurna dalam setiap tegukan. Latte kami diracik dengan karakter kopi yang kuat namun tetap lembut di lidah, berpadu harmonis dengan sentuhan susu yang creamy. Disajikan dalam kemasan cup yang praktis, minuman ini adalah pilihan ideal bagi Anda yang mengutamakan cita rasa kopi yang murni, autentik, dan menenangkan.' },
            {id: 17, name: 'Es Kopi', img:'b_5.jpg', price: 13000, category: 'coffee', deskripsi: 'Nikmati kesegaran murni dalam setiap tegukan. Es kopi kami diracik dengan karakter kopi pilihan yang bold dan clean, dipadukan dengan sentuhan manis yang seimbang untuk menyempurnakan hari Anda.' },
            {id: 18, name: 'Kopi Susu panas', img:'b_5.jpg', price: 12000, category: 'coffee', deskripsi: 'Awali hari Anda dengan kehangatan yang sempurna. Kopi susu panas kami adalah perpaduan harmonis antara bold-nya biji kopi pilihan dengan sentuhan tekstur yang sangat creamy dan lembut. Diracik khusus untuk menciptakan keseimbangan rasa yang rich dan menenangkan di setiap tegukan. Sangat pas untuk menjadi teman setia di pagi yang dingin atau momen santai Anda.' },
            {id: 19, name: 'Kopi Hitam Panas', img:'b_3.jpg', price: 10000, category: 'coffee', deskripsi: 'Kreasi kopi hitam istimewa yang menonjolkan kekayaan aroma biji kopi pilihan. Diracik dengan keseimbangan rasa yang presisi untuk menjamin pengalaman minum kopi yang konsisten, berkarakter, dan nikmat. Nikmati sensasi kopi hitam yang autentik dan berkelas dalam setiap cup.' },
            {id: 20, name: 'Ice Americano', img:'b_3.jpg', price: 11000, category: 'coffee', deskripsi: 'Rasakan esensi kopi yang sesungguhnya. Americano kami menghadirkan karakter kopi yang kuat, bold, dan murni dalam setiap tegukannya. Tanpa tambahan pemanis, Anda dapat menikmati profil rasa asli kopi yang bersih dan menyegarkan. Disajikan dalam kemasan cup yang praktis, ini adalah pilihan tepat bagi para pecinta kopi sejati yang mengutamakan cita rasa otentik.' },
            {id: 21, name: 'Lychee Coffee', img:'b_6.jpg', price: 17000, category: 'coffee', deskripsi: 'Eksplorasi rasa kopi yang berbeda dengan nuansa buah tropis yang manis dan elegan. Dibuat dengan teknik racikan spesial untuk menjamin keseimbangan rasa yang konsisten dan menyegarkan di setiap cup. Nikmati keunikan cita rasa yang memanjakan selera Anda dalam kemasan praktis yang siap menemani hari Anda.' },
            {id: 22, name: 'Strawberry Coffee', img:'b_6.jpg', price: 17000, category: 'coffee', deskripsi: 'Rasakan harmoni unik antara kekuatan kopi pilihan yang bold dengan kesegaran buah beri yang manis dan memikat. Minuman ini diracik dengan teknik khusus untuk menghasilkan profil rasa yang seimbang, memberikan sensasi fruity yang menyegarkan di setiap tegukannya. Disajikan dalam kemasan cup praktis, ini adalah pilihan tepat bagi Anda yang mencari pengalaman minum kopi yang ceria dan berbeda.' },
            {id: 23, name: 'Tropical Mango', img:'b_6.jpg', price: 17000, category: 'coffee', deskripsi: 'Hadirkan suasana liburan tropis dalam setiap tegukan. Perpaduan sempurna antara karakter kopi yang bold dengan manisnya sentuhan buah mangga yang eksotis. Racikan spesial kami menghasilkan profil rasa yang cerah, menyegarkan, dan seimbang, memberikan sensasi unik yang akan membangkitkan semangat Anda. Disajikan dalam kemasan cup praktis yang siap menemani aktivitas Anda dengan keceriaan rasa buah alami.' },
            {id: 24, name: 'Pink Grape', img:'b_6.jpg', price: 17000, category: 'coffee', deskripsi: 'Temukan sensasi rasa kopi yang belum pernah Anda bayangkan sebelumnya. Perpaduan karakter kopi yang bold dengan sentuhan elegan dari ekstrak anggur premium. Racikan spesial kami menghasilkan profil rasa yang sophisticated—paduan antara aroma kopi yang kuat dengan kesegaran manis dari buah anggur yang menggoda. Disajikan dalam kemasan cup praktis, ini adalah pilihan tepat bagi mereka yang berani mencoba inovasi rasa yang berkelas.' },
            {id: 25, name: 'Jasmine', img:'b_6.jpg', price: 20000, category: 'coffee', deskripsi: 'Rasakan keanggunan dalam secangkir kopi. Perpaduan harmonis antara karakter kopi pilihan yang mantap dengan sentuhan aroma bunga melati yang harum dan menenangkan. Racikan spesial kami menghasilkan tekstur yang lembut, creamy, dan meninggalkan kesan rasa yang bersih di setiap tegukan. Disajikan dalam kemasan cup praktis, ini adalah cara sempurna untuk menikmati momen relaksasi dengan nuansa yang mewah.' },
            {id: 26, name: 'Sakura', img:'b_6.jpg', price: 20000, category: 'coffee', deskripsi: 'Kopi dengan sentuhan spesial nuansa sakura yang autentik. Menawarkan harmoni antara kekuatan kopi dengan wangi bunga yang lembut dan tekstur yang sangat halus. Dibuat dari bahan-bahan berkualitas premium untuk memberikan pengalaman minum kopi yang konsisten dan memanjakan. Nikmati kelezatan istimewa ini kapan saja.' },
            {id: 27, name: 'Osmantus', img:'b_6.jpg', price: 20000, category: 'coffee', deskripsi: 'Kopi susu dengan sentuhan spesial aroma bunga Osmanthus yang autentik. Menawarkan perpaduan antara kekuatan karakter kopi dengan wangi bunga yang lembut dan tekstur yang sangat halus. Dibuat dari bahan-bahan berkualitas premium untuk memberikan pengalaman minum kopi yang konsisten dan memanjakan.' },
            {id: 28, name: 'Matcha latte shincan', img:'b_6.jpg', price: 22000, category: 'noncoffee', deskripsi: 'Ingin sesuatu yang berbeda untuk menemani hari Anda? Es Matcha Latte Shincan kami hadir dengan profil rasa yang rich, bold, dan super creamy. Perpaduan bahan-bahan pilihan kami menghasilkan tekstur yang begitu halus dan lembut di lidah. Sangat pas untuk Anda yang mendambakan minuman manis-gurih dengan sensasi teh hijau yang ikonik. One sip, and you’ll fall in love with the creaminess!' },
            {id: 29, name: 'Matcha latte coconut', img:'b_6.jpg', price: 22000, category: 'noncoffee', deskripsi: 'Sebuah perpaduan istimewa antara karakter teh hijau premium dengan sentuhan nuansa tropis yang lembut dan elegan. Dibuat dengan racikan khusus untuk menjamin tekstur yang halus, kaya rasa, dan sangat creamy. Nikmati kelezatan unik yang memanjakan selera di setiap tegukannya. Authentic, smooth, and refreshing.' },
            {id: 30, name: 'Matcha latte pistachio', img:'b_6.jpg', price: 22000, category: 'noncoffee', deskripsi: 'Rasakan perpaduan dua dunia yang sempurna dalam satu cup. Keanggunan teh hijau premium berpadu harmonis dengan sentuhan rasa kacang yang gurih, elegan, dan eksklusif. Racikan spesial kami menghasilkan tekstur yang begitu creamy, lembut, dan memanjakan lidah di setiap tegukannya. Minuman ini adalah pilihan tepat bagi Anda yang mendambakan pengalaman rasa yang unik, mewah, dan benar-benar memuaskan.' },
            {id: 31, name: 'Coklat', img:'b_6.jpg', price: 18000, category: 'noncoffee', deskripsi: 'Temukan kembali kenikmatan cokelat dalam bentuk yang paling murni. Racikan spesial kami menghasilkan perpaduan cokelat yang kaya, dalam tekstur yang begitu lembut dan creamy. Disajikan dingin untuk memberikan kesegaran yang maksimal, minuman ini adalah pilihan tepat bagi Anda yang merindukan rasa cokelat autentik yang mewah dan menenangkan di setiap tegukan.' },
            {id: 32, name: 'Matcha', img:'image56.jpg', price: 18000, category: 'noncoffee', deskripsi: 'Butuh sesuatu yang segar dan mood booster? Es Matcha kami hadir dengan profil rasa yang rich, lembut, dan sangat memanjakan. Formula rahasia kami menciptakan keseimbangan sempurna antara aroma teh hijau yang khas dengan tekstur yang velvety. Smooth, refreshing, and absolutely addictive! Rasakan sensasi teh hijau premium dalam setiap tegukannya.' },
            {id: 33, name: 'Taro', img:'b_6.jpg', price: 18000, category: 'noncoffee', deskripsi: 'Rasakan kelembutan rasa yang unik dan memikat dalam setiap tegukan. Es Taro kami menghadirkan perpaduan rasa yang khas dengan sentuhan tekstur yang sangat creamy dan velvety. Dibuat dengan racikan spesial yang menonjolkan keseimbangan antara rasa manis yang lembut dan aroma yang menggoda. Disajikan dingin, minuman ini adalah pilihan tepat untuk memanjakan hari Anda dengan sensasi rasa yang istimewa.' },
            {id: 34, name: 'Red Velvet', img:'b_6.jpg', price: 18000, category: 'noncoffee', deskripsi: 'Perpaduan istimewa rasa Red Velvet yang autentik dengan tekstur yang halus dan kaya rasa. Dibuat dengan racikan khusus kami untuk menjamin konsistensi rasa yang lembut dan memanjakan di setiap cup. Nikmati pengalaman minum premium dengan sentuhan kemewahan di setiap tegukannya.' },
            {id: 35, name: 'Mangga', img:'b_6.jpg', price: 17000, category: 'noncoffee', deskripsi: 'Rasakan kesegaran musim panas dalam setiap tegukan. Es Mangga kami menghadirkan cita rasa buah tropis yang autentik, dengan profil rasa yang cerah dan menyegarkan. Diracik dengan keseimbangan manis yang sempurna, minuman ini memberikan sensasi light dan clean yang memanjakan tenggorokan. Disajikan dalam kemasan cup praktis, ini adalah pilihan terbaik untuk melepas dahaga Anda di tengah hari.' },
            {id: 36, name: 'Jeruk Mandarin', img:'b_6.jpg', price: 17000, category: 'noncoffee', deskripsi: 'Rasakan sensasi kesegaran jeruk mandarin yang khas dengan sentuhan manis yang elegan. Minuman ini menawarkan profil rasa buah yang ceria, cerah, dan sangat menyegarkan di setiap tegukannya. Dibuat dengan racikan khusus untuk menghasilkan keseimbangan rasa yang sempurna antara kesegaran alami buah dan manis yang pas. Disajikan dingin, ini adalah pilihan terbaik untuk menemani hari Anda dengan kesegaran yang memanjakan.' },
            {id: 37, name: 'Lychee Tea', img:'b_6.jpg', price: 15000, category: 'noncoffee', deskripsi: 'Ingin melepas dahaga dengan cara yang lebih berkesan? Es Lychee Tea kami hadir dengan perpaduan rasa buah yang vibrant dan sentuhan teh yang menenangkan. Formula rahasia kami menciptakan keseimbangan sempurna, menjadikannya minuman yang light, manis, dan sangat memanjakan. Simple, elegant, and perfectly refreshing! Temukan kesegaran khas buah tropis dalam setiap cup-nya.' },
            {id: 38, name: 'Mango Tea', img:'b_6.jpg', price: 15000, category: 'noncoffee', deskripsi: 'Nikmati perpaduan harmonis antara karakter teh pilihan yang light dengan kesegaran buah mangga tropis yang eksotis. Racikan spesial kami menghasilkan profil rasa yang bright, menyegarkan, dan memiliki keseimbangan manis yang sempurna di setiap tegukan. Disajikan dingin dalam kemasan praktis, minuman ini adalah teman sempurna untuk membangkitkan suasana hari Anda dengan kesegaran buah yang autentik.' },
            {id: 39, name: 'Strawberry Tea', img:'b_6.jpg', price: 15000, category: 'noncoffee', deskripsi: 'Nikmati harmoni rasa yang menyegarkan dalam satu cup. Perpaduan istimewa antara teh pilihan dengan sentuhan aroma buah beri merah yang manis dan menenangkan. Racikan spesial kami menghasilkan profil rasa yang bright, ringan, dan memiliki keseimbangan manis yang pas di lidah. Pilihan sempurna bagi Anda yang mendambakan kesegaran alami dengan nuansa rasa yang elegan dan berkelas.' },
            {id: 40, name: 'Rashberry Tea', img:'b_6.jpg', price: 15000, category: 'noncoffee', deskripsi: 'Ingin mencoba sesuatu yang berbeda dari teh biasanya? Es Raspberry Tea kami hadir dengan perpaduan rasa yang vibrant dan penuh karakter. Formula rahasia kami menyeimbangkan aroma teh yang menenangkan dengan intensitas rasa buah beri yang menggoda. Smooth, tangy, and absolutely refreshing! Sempurna untuk menemani hari Anda dengan sensasi rasa yang istimewa dan menyegarkan' },
            {id: 41, name: 'Virgin Mojito', img:'b_6.jpg', price: 14000, category: 'mocktail', deskripsi: 'Rasakan ledakan kesegaran yang instan dalam setiap tegukan. Virgin Mojito kami diracik dengan sentuhan citrus yang tajam dan menyegarkan, berpadu sempurna dengan sensasi soda yang bubbly dan meletup-letup di lidah. Dibuat dengan keseimbangan manis yang pas untuk menyeimbangkan kesegaran alaminya, minuman ini adalah pilihan tepat bagi Anda yang menginginkan kesegaran murni yang membangkitkan semangat.' },
            {id: 42, name: 'Mojito Mint', img:'b_6.jpg', price: 17000, category: 'mocktail', deskripsi: 'Rasakan sensasi kesegaran yang benar-benar memanjakan. Perpaduan antara karakter citrus yang tajam dengan sensasi dingin dari aroma daun mint alami, menciptakan harmoni rasa yang sangat clean dan menyegarkan. Dengan sentuhan sparkling yang lembut di lidah, minuman ini adalah pilihan tepat untuk mengembalikan semangat Anda. Rasakan kesegaran murni yang menenangkan di setiap tegukannya.' },
            {id: 43, name: 'Markisa', img:'b_6.jpg', price: 16000, category: 'mocktail', deskripsi: 'Sebuah kreasi istimewa yang memadukan kesegaran alami buah markisa pilihan dengan sentuhan sparkling yang elegan. Dibuat dengan racikan khusus kami untuk menjamin konsistensi rasa yang ringan, jernih, dan menyegarkan di setiap cup. Nikmati pengalaman rasa buah yang autentik dan memanjakan kapan pun Anda mau.' },
            {id: 44, name: 'Pink Lime', img:'b_6.jpg', price: 18000, category: 'mocktail', deskripsi: 'Sebuah kreasi istimewa yang memadukan kesegaran citrus premium dengan nuansa buah yang manis dan elegan. Dibuat dengan racikan khusus kami untuk menjamin konsistensi rasa yang ringan, jernih, dan menyegarkan di setiap cup. Nikmati kelezatan unik dengan sentuhan warna yang memanjakan mata dan lidah.' },
            {id: 45, name: 'Blue Sea', img:'b_6.jpg', price: 16000, category: 'mocktail', deskripsi: 'Temukan sensasi kesegaran yang membawa Anda seolah sedang berada di tepi pantai yang tenang. Minuman ini memadukan kesegaran citrus premium dengan sentuhan rasa buah tropis yang eksotis, menciptakan warna biru yang memikat dan rasa yang sangat menyegarkan. Dengan sensasi sparkling yang lembut, setiap tegukan memberikan pengalaman rasa yang unik, bersih, dan memanjakan.' },
            {id: 46, name: 'Fruity Mix', img:'b_6.jpg', price: 16000, category: 'mocktail', deskripsi: 'Nikmati ledakan kesegaran dalam setiap tegukan. Minuman ini adalah harmoni sempurna antara kesegaran citrus yang tajam dengan perpaduan berbagai karakter buah pilihan yang manis dan menggugah selera. Dengan sensasi sparkling yang ringan dan elegan, Fruity Mix kami menawarkan pengalaman rasa yang kompleks namun tetap menyegarkan. Pilihan tepat bagi Anda yang ingin menikmati sensasi buah yang berlimpah dalam satu cup praktis.' },
            {id: 47, name: 'Milk Butterscotch', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Nikmati kelembutan yang memanjakan dalam setiap tegukan. Es Milk Butterscotch kami diracik dengan perpaduan susu pilihan yang rich dan sentuhan butterscotch yang manis, keemasan, dan elegan. Karakter rasa karamel yang buttery berpadu sempurna dengan tekstur yang sangat halus, memberikan pengalaman minum yang mewah dan menenangkan. Pilihan terbaik bagi Anda yang mendambakan kenyamanan manis dalam satu cup' },
            {id: 48, name: 'Milk Caramel', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Manjakan harimu dengan kesegaran yang rich dan manis yang pas. Es Milk Caramel kami hadir dengan perpaduan tekstur yang begitu lembut dan creamy, serta aroma karamel yang menggoda. Formula rahasia kami menciptakan keseimbangan sempurna yang bikin ketagihan. Smooth, rich, and perfectly sweet! Temukan kenyamanan rasa dalam satu cup yang memanjakan lidah Anda.' },
            {id: 49, name: 'Milk Hazelnut', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Kreasi istimewa yang memadukan kelembutan susu premium dengan nuansa rasa hazelnut yang hangat dan autentik. Dibuat dengan racikan khusus kami untuk menjamin konsistensi rasa yang halus, kaya, dan memanjakan di setiap cup. Nikmati pengalaman minum yang mewah dan creamy kapan pun Anda butuhkan.' },
            {id: 50, name: 'Milk Cream Cheese', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Temukan sensasi rasa yang tak terlupakan. Minuman ini menawarkan perpaduan sempurna antara kelembutan susu pilihan dengan sentuhan rasa keju yang rich, gurih, dan manis secara harmonis. Racikan spesial kami menghasilkan tekstur yang sangat creamy dan velvety, memberikan pengalaman minum yang mewah dengan profil rasa yang unik. Pilihan tepat bagi Anda yang mendambakan sensasi rasa gurih-manis yang elegan dalam satu cup.' },
            {id: 51, name: 'Milk Tiramisu', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Ingin menikmati sesuatu yang manis dan berkelas? Es Milk Tiramisu kami hadir dengan profil rasa yang rich, lembut, dan sangat memanjakan lidah. Formula rahasia kami menciptakan perpaduan rasa kopi yang lembut dengan sentuhan manis yang harmonis, memberikan sensasi smooth di setiap tegukan. Rich, sophisticated, and absolutely satisfying! Temukan sensasi tiramisu dalam kemasan praktis yang siap menemani momen santai Anda.' },
            {id: 52, name: 'Milk Banana', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Rasakan kelembutan yang memanjakan dalam setiap tegukan. Es Milk Banana kami menyajikan perpaduan harmonis antara kelembutan susu pilihan dengan aroma buah pisang yang manis, lembut, dan aromatik. Racikan spesial kami menghasilkan tekstur yang sangat velvety dan creamy, memberikan kenyamanan rasa yang ringan namun berkesan. Pilihan tepat untuk menemani waktu santai Anda dengan kesegaran manis yang alami.' },
            {id: 53, name: 'Milk Pistachio', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Nikmati sensasi rasa yang unik dan eksotis dalam setiap tegukan. Es Milk Pistachio kami diracik dengan memadukan kelembutan susu pilihan dengan aroma kacang premium yang gurih, lembut, dan elegan. Racikan spesial kami menghasilkan tekstur yang sangat creamy dan velvety, memberikan pengalaman minum yang mewah dengan profil rasa yang berbeda dari yang lain. Pilihan sempurna bagi Anda yang mendambakan sensasi rasa kacang yang kaya dan berkelas.' },
            {id: 54, name: 'Milk Coconut', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Sebuah kreasi istimewa yang memadukan kelembutan susu premium dengan nuansa rasa kelapa yang autentik dan elegan. Dibuat dengan racikan khusus kami untuk menjamin konsistensi rasa yang halus, kaya, dan memanjakan di setiap cup. Nikmati pengalaman minum yang manis, lembut, dan menyegarkan kapan pun Anda inginkan.' },
            {id: 55, name: 'Milk Almond', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Nikmati kelembutan yang memikat dengan sentuhan rasa kacang yang eksklusif. Es Milk Almond kami diracik dengan memadukan kelembutan susu pilihan dengan aroma kacang almond yang lembut, manis, dan aromatik. Racikan spesial kami menghasilkan tekstur yang sangat creamy dan smooth, memberikan pengalaman minum yang mewah dengan profil rasa yang bersih namun kaya. Pilihan sempurna bagi Anda yang mendambakan sensasi rasa kacang yang elegan dan menenangkan' },
            {id: 56, name: 'Milk Pandan', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Rasakan kehangatan aroma khas dedaunan hijau tropis yang berpadu sempurna dengan kelembutan susu premium. Es Milk Pandan kami menyajikan sensasi rasa yang menenangkan, dengan aroma wangi yang ikonik dan tekstur yang sangat velvety. Racikan spesial kami menghasilkan profil rasa yang unik, manis yang pas, dan sangat memanjakan lidah. Sebuah persembahan istimewa untuk Anda yang mencari cita rasa autentik dengan sentuhan yang elegan.' },
            {id: 57, name: 'Milk Vanila', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Butuh sesuatu yang manis dan memanjakan lidah? Es Milk Vanila kami hadir dengan profil rasa yang rich, lembut, dan sangat memikat. Formula rahasia kami menciptakan keseimbangan sempurna antara aroma vanila yang harum dengan kelembutan susu yang creamy. Smooth, sweet, and perfectly balanced! Rasakan kemewahan rasa klasik dalam satu cup yang siap membuat hari Anda terasa jauh lebih manis.' },
            {id: 58, name: 'Milk Jasmine', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Temukan ketenangan dalam setiap tegukan. Minuman ini memadukan kelembutan susu pilihan dengan aroma bunga melati yang harum, lembut, dan menenangkan. Racikan spesial kami menghasilkan tekstur yang sangat velvety dan smooth, memberikan pengalaman minum yang mewah dengan profil rasa yang unik dan berkelas. Sebuah persembahan sempurna bagi Anda yang mendambakan kenyamanan rasa dengan sentuhan aroma bunga yang elegan.' },
            {id: 59, name: 'Milk Sakura', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Kreasi istimewa yang memadukan kelembutan susu premium dengan nuansa rasa bunga sakura yang autentik dan elegan. Dibuat dengan racikan khusus kami untuk menjamin konsistensi rasa yang halus, kaya, dan memanjakan di setiap cup. Nikmati pengalaman minum yang unik, manis, dan beraroma kapan pun Anda butuhkan.' },
            {id: 60, name: 'Milk Osmantus', img:'b_6.jpg', price: 18000, category: 'milk', deskripsi: 'Nikmati harmoni rasa yang eksotis dan memikat dalam setiap tegukan. Es Milk Osmanthus kami merangkum kelembutan susu pilihan dengan sentuhan aroma bunga khas yang lembut, manis, dan begitu menenangkan. Racikan spesial kami menghasilkan tekstur yang sangat creamy dan smooth, memberikan pengalaman minum yang mewah dengan profil rasa yang unik dan berbeda. Pilihan sempurna bagi Anda yang mendambakan kenyamanan rasa dengan aroma bunga yang elegan.' }, 
        ],
        rupiah(number) {
            return new Intl.NumberFormat('id-ID', {
                style: 'currency',
                currency: 'IDR',
                minimumFractionDigits: 0,
            }).format(number);
        },
        filteredItems() {
        return this.items.filter((item) => {
            // 1. Logika Pencarian
            const matchSearch = item.name.toLowerCase().includes(Alpine.store('products').searchQuery.toLowerCase());
            
            // 2. Logika Kategori (Sesuaikan dengan variabel kategori Anda)
            const matchCategory = this.kategori === 'all' || item.category === this.kategori;

            return matchSearch && matchCategory;
        });
        },
    }));

    Alpine.store('cart', {
        items: [],
        total: 0,
        quantity: 0,
        add(newItem) {
            const cartItem = this.items.find((item) => item.id === newItem.id);
            if (!cartItem) {
                this.items.push({...newItem, quantity: 1, total: newItem.price });
                this.quantity++;
                this.total += newItem.price;
            } else {
                this.items = this.items.map((item) => {
                    if (item.id !== newItem.id) {
                        return item;
                    } else {
                        item.quantity++;
                        item.total = item.price * item.quantity;
                        this.quantity++;
                        this.total += item.price;
                        return item;
                    }
                });
            }
        },
        remove(id) {
            const cartItem = this.items.find((item) => item.id === id);
            if (cartItem.quantity > 1) {
                this.items = this.items.map((item) => {
                    if (item.id !== id) {
                        return item;
                    } else {
                        item.quantity--;
                        item.total = item.price * item.quantity;
                        this.quantity--;
                        this.total -= item.price;
                        return item;
                    }
                });
            } else if (cartItem.quantity === 1) {
                this.items = this.items.filter((item) => item.id !== id);
                this.quantity--;
                this.total -= cartItem.price;
            }
        },
    });

    // Logic untuk toggle input search (UI)
    // Logic untuk toggle input search (UI)
    const searchForm = document.querySelector('.search-form');
    const searchBox = document.querySelector('#search-box');

    document.querySelector('#search-button').onclick = (e) => {
        searchForm.classList.toggle('active');
        searchBox.focus();
        e.preventDefault();
    };

});